In [3]:
# import the necessary packages
import numpy as np
import argparse
import imutils
import cv2

def sort_contours(cnts, method="left-to-right"):
	# initialize the reverse flag and sort index
	reverse = False
	i = 0
 
	# handle if we need to sort in reverse
	if method == "right-to-left" or method == "bottom-to-top":
		reverse = True
  
	# handle if we are sorting against the y-coordinate rather than
	# the x-coordinate of the bounding box
	if method == "top-to-bottom" or method == "bottom-to-top":
		i = 1
  
	# construct the list of bounding boxes and sort them from top to
	# bottom
	boundingBoxes = [cv2.boundingRect(c) for c in cnts]
	(cnts, boundingBoxes) = zip(*sorted(zip(cnts, boundingBoxes),
		key=lambda b:b[1][i], reverse=reverse))
 
	# return the list of sorted contours and bounding boxes
	return (cnts, boundingBoxes)

def draw_contour(image, c, i):
	# compute the center of the contour area and draw a circle
	# representing the center
	M = cv2.moments(c)
	cX = int(M["m10"] / M["m00"])
	cY = int(M["m01"] / M["m00"])
 
	# draw the countour number on the image
	cv2.putText(image, "#{}".format(i + 1), (cX - 20, cY), cv2.FONT_HERSHEY_SIMPLEX,
		1.0, (255, 255, 255), 2)
 
	# return the image with the contour number drawn on it
	return image

# construct the argument parser and parse the arguments
# ap = argparse.ArgumentParser()
# ap.add_argument("-i", "--image", required=True, help="Path to the input image")
# ap.add_argument("-m", "--method", required=True, help="Sorting method")
# args = vars(ap.parse_args())
# load the image and initialize the accumulated edge image
image_path = 'sortImage.png'
image = cv2.imread(image_path) #args["image"])
accumEdged = np.zeros(image.shape[:2], dtype="uint8")
print((image.shape)[0:2])
# loop over the blue, green, and red channels, respectively
for chan in cv2.split(image):
	# blur the channel, extract edges from it, and accumulate the set
	# of edges for the image
	chan = cv2.medianBlur(chan, 11)
	edged = cv2.Canny(chan, 50, 200)
	accumEdged = cv2.bitwise_or(accumEdged, edged)

# show the accumulated edge map
# cv2.imshow("Edge Map", accumEdged)

# find contours in the accumulated image, keeping only the largest
# ones
cnts = cv2.findContours(accumEdged.copy(), cv2.RETR_EXTERNAL,
	cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)
cnts = sorted(cnts, key=cv2.contourArea, reverse=True)[:5]
orig = image.copy()

# loop over the (unsorted) contours and draw them
for (i, c) in enumerate(cnts):
	orig = draw_contour(orig, c, i)
 
# show the original, unsorted contour image
# cv2.imshow("Unsorted", orig)
# print(cnts)

# sort the contours according to the provided method
(cnts, boundingBoxes) = sort_contours(cnts,"top-to-bottom")   #(method=args["method"])
print(boundingBoxes)
print(cnts)

	# # loop over the (now sorted) contours and draw them
	# for (i, c) in enumerate(cnts):
	# 	draw_contour(image, c, i)
	
	# # show the output image
	# cv2.imshow("Sorted", image)
	# cv2.waitKey(0)

(883, 489)
((101, 31, 291, 173), (99, 256, 287, 144), (333, 573, 33, 34), (110, 576, 33, 33), (179, 733, 33, 34))
(array([[[350,  31]],

       [[349,  32]],

       [[307,  32]],

       [[306,  33]],

       [[305,  33]],

       [[304,  32]],

       [[297,  32]],

       [[296,  33]],

       [[285,  33]],

       [[284,  32]],

       [[277,  32]],

       [[276,  33]],

       [[262,  33]],

       [[261,  34]],

       [[256,  34]],

       [[255,  33]],

       [[254,  34]],

       [[201,  34]],

       [[200,  35]],

       [[180,  35]],

       [[179,  36]],

       [[150,  36]],

       [[149,  37]],

       [[120,  37]],

       [[119,  38]],

       [[106,  38]],

       [[101,  43]],

       [[101,  74]],

       [[102,  75]],

       [[102,  76]],

       [[101,  77]],

       [[101,  81]],

       [[102,  82]],

       [[102,  89]],

       [[103,  90]],

       [[103, 116]],

       [[104, 117]],

       [[104, 148]],

       [[105, 149]],

       [[105, 166]],

     

In [6]:
# print(type(cnts))
# print(type(cnts[1]))
print(len(cnts))
print(type(cnts))

for i in range(len(cnts)):
    print('*'*50)
    print ('length of ', i,':', len(cnts[i]))
    print(type(cnts[i]))
    
    print(type(cnts[i][0]))
    print(len(cnts[i][0]))
    print(cnts[i][0])
    print(cnts[i][1])
    
    
    print((cnts[i][0][0]))
    

5
<class 'tuple'>
**************************************************
length of  0 : 138
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
[[350  31]]
[[349  32]]
[350  31]
**************************************************
length of  1 : 50
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
[[148 256]]
[[147 257]]
[148 256]
**************************************************
length of  2 : 51
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
[[351 573]]
[[350 574]]
[351 573]
**************************************************
length of  3 : 46
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
[[124 576]]
[[123 577]]
[124 576]
**************************************************
length of  4 : 52
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
1
[[195 733]]
[[194 734]]
[195 733]


$ python sorting_contours.py --image images/image_01.png --method "top-to-bottom"


In [7]:
a = [1,3,4,5]
dt = np.dtype(np.int32) 

for (i, c) in enumerate(a):
	print(i, ' ', c)
 
b = np.array([2,4,6],dtype = dt)


print(type(b))

cnts[0].shape

# print(dt)

0   1
1   3
2   4
3   5
<class 'numpy.ndarray'>


(138, 1, 2)

In [1]:
# import the necessary packages
import numpy as np
import argparse
import imutils
import cv2

def box_to_contours(_img_path, _img_label):
    fl = open(_img_label, 'r')
    coords = fl.readlines()
    fl.close()
    
    img = cv2.imread(_img_path) #args["image"])
    img_h, img_w = img.shape[0:2]
    res = ()
    
    for dt in coords:            
        # class x_center y_center width height
        dt_split = dt.split(' ')
        dt_split_int = list(map(lambda x: float(x), dt_split))
        _, tmp_x_cen, tmp_y_cen, tmp_box_w, tmp_box_h = dt_split_int
        # get ABCD (numpy array)
        tmp_ABCD = get_cornercoords(tmp_x_cen, tmp_y_cen, tmp_box_w, tmp_box_h, img_w, img_h)
        # print(tmp_xy1xy2)
            # draw.rectangle(tmp_xy1xy2, outline=(0, 0, 0, 255), width=10)
        res = res + (tmp_ABCD, )
    
    # print(res)

    (cnts, boundingBoxes) = sort_contours(res,"top-to-bottom")   #(method=args["method"])

    # loop over the (now sorted) contours and draw them
    for (i, c) in enumerate(cnts):
        draw_contour(img, c, i)

    # show the output image
    imS = cv2.resize(img, (500, 800))     
    cv2.imshow("Sorted", imS)

    # cv2.imshow('bounding', cv2.resize(cv2.drawContours(img, res, -1, (0,255,0), 3), (600, 900))  )

    cv2.waitKey(0)
    return res
    
    
def get_cornercoords(x_center, y_center, box_width, box_height, image_width, image_height):
    # class x_center y_center width height
    x1 = image_width * (x_center - box_width / 2)
    x2 = image_width * (x_center + box_width / 2)
    
    y1 = image_height * (y_center - box_height / 2)
    y2 = image_height * (y_center + box_height / 2)
    
    corners = [[[x1, y1]], [[x2,y1]], [[x2,y2]], [[x1,y2]]]
    corners_np = np.array(corners, dtype=np.dtype(np.int32))
    
    return corners_np

image_path = 'datasets/data_th/images/val/THM_255.jpg'
label_path = 'datasets/data_th/labels/val/THM_255.txt'

clist = box_to_contours(image_path, label_path)
# print((t[0]).shape)
# print(clist)



NameError: name 'sort_contours' is not defined

In [18]:
v = [3,3,34,1,1,1,1,2,3,4,3,1,2]
any([1]*3 == v[i:i+3] for i in range(len(v) - 1))

type([1]*3)

list